sudo: required
language: python
python:
  - "3.4"
  - "3.5"

before_install:
  - wget https://github.com/yandex/tomita-parser/releases/download/v1.0/libmystem_c_binding.so.linux_x64.zip
  - unzip libmystem_c_binding.so.linux_x64.zip
  - sudo cp libmystem_c_binding.so /usr/lib/
  - pip install -r requirements.txt

script:
  - nosetests
